#!/bin/sh /etc/rc.common
# Example script
# Copyright (C) 2007 OpenWrt.org

START=10
STOP=15
PIDFILE="/var/run/sniff.pid"

start() {
        if [ -f $PIDFILE  ]; then
                echo "Already Running"
        else
                (python /usr/bin/sniff.py >/dev/null 2>&1 )&
                echo "$!" > $PIDFILE
        fi
}

stop() {
        if [ -f $PIDFILE ]; then
                read PID <$PIDFILE
                echo "Stopped $PID"
                kill -9 $PID
                rm $PIDFILE
        else
                echo "Not Running"
        fi

}

